version: "3.4"
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-alpine"
    restart: unless-stopped
  heimdalld:
    build: &ref_0
      args:
        UPSTREAM_VERSION: v0.2.12
      context: ./build/heimdall
      dockerfile: Dockerfile
    volumes:
      - "/mnt/ethereum/heimdall:/root/.heimdalld"
    ports:
      - "26656:26656"
    depends_on:
      - rabbitmq
    environment:
      - MONIKER=
      - SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/heimdall-snapshot-2022-10-26.tar.gz
      - BOOTSTRAP=1
      - ETH1_RPC_URL=http://fullnode.dappnode:8545
      - BOOTNODES=
    restart: unless-stopped
  heimdallr:
    environment:
      - REST_SERVER=1
      - ETH1_RPC_URL=http://fullnode.dappnode:8545
    build: *ref_0
    volumes:
      - "/mnt/ethereum/heimdall:/root/.heimdalld"
    depends_on:
      - heimdalld
    restart: unless-stopped
  bor:
    build:
      args:
        UPSTREAM_VERSION: v0.2.17
      context: ./build/bor
      dockerfile: Dockerfile
    environment:
      - SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/bor-fullnode-snapshot-2022-10-21.tar.gz
      - BOOTSTRAP=1
      - MAXPEERS=
    volumes:
      - "/mnt/ethereum/bor:/datadir"
    ports:
      - "40303:40303"
      - "40303:40303/udp"
    depends_on:
      - heimdallr
    restart: unless-stopped
volumes:
  rabbitmq: {}
